name: fetch-and-push

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 16 * * *'  # Setiap hari jam 23:00 WIB

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install libraries
        run: pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python fetch_all.py

      - name: Commit and push result
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add result.json
          git commit -m "Update result $(date)" || echo "No changes"
          git push
